### ISSUE TITLE
Confusion re when comments are due/how many days are left

### ISSUE THREAD

**Issue by quepol** [18F/epa-notice#450]
On the home page, it says the comments are due in 57 days. On the proposal page, it says 55 days.

![home page - 57 days](https://cloud.githubusercontent.com/assets/1841120/17431303/427dba08-5aae-11e6-96e9-3a1a5e0869a5.png)
![proposal page - 55 days](https://cloud.githubusercontent.com/assets/1841120/17431298/3b69879c-5aae-11e6-87c0-00cc4dfe831c.png)

**Comment by tadhg-ohiggins** [comment]
Worse, it turns out that in production, when you refresh the page you can get different days per refresh—and that they tend not to be accurate.

This appears to be due to caching, and possibly due to the interaction between the cache timeout setting and the Django `key_prefix` setting.

This needs to be fixed on both the home page and the proposal page; I'm currently working through a candidate fix for the home page.

**Comment by tadhg-ohiggins** [comment]
https://github.com/18F/epa-notice/pull/451 addresses this by removing the long-term caching from the homepage and from the intro page, at the expense of some performance (the middleware now caches those pages for only 600 seconds). Right now this is on the demo server and I will very likely push it to production tomorrow morning.

**Comment by tadhg-ohiggins** [comment]
Fixed in #451 and pushed to production, so closing. Also, opened new issue to track resulting problems: https://github.com/18F/epa-notice/issues/452
